import type { Bank, TimeDeposit } from "@/lib/types";

export const banks: Bank[] = [
  { id: "cimb", name: "CIMB", taxRate: 0.2 },
  { id: "cimb-prime", name: "CIMB Prime", taxRate: 0.2 },
  { id: "tonik", name: "Tonik", taxRate: 0.2 },
  { id: "ownbank", name: "OwnBank", taxRate: 0.2 },
  { id: "maribank", name: "MariBank", taxRate: 0.2 },
  { id: "maya", name: "Maya", taxRate: 0.2 },
  { id: "uno", name: "Uno", taxRate: 0.2 },
];

export const deposits: TimeDeposit[] = [
  {
    id: "td-001",
    bankId: "tonik",
    name: "Tonik - 12M",
    principal: 320000,
    startDate: "2026-01-18",
    termMonths: 12,
    interestMode: "simple",
    interestTreatment: "reinvest",
    compounding: "monthly",
    taxRateOverride: 0.2,
    flatRate: 0.065,
    tiers: [{ upTo: null, rate: 0.065 }],
    payoutFrequency: "maturity",
    status: "active",
  },
  {
    id: "td-002",
    bankId: "ownbank",
    name: "OwnBank - 180",
    principal: 210000,
    startDate: "2026-02-03",
    termMonths: 6,
    interestMode: "simple",
    interestTreatment: "reinvest",
    compounding: "monthly",
    taxRateOverride: 0.2,
    flatRate: 0.048,
    tiers: [{ upTo: null, rate: 0.048 }],
    payoutFrequency: "maturity",
    status: "active",
  },
  {
    id: "td-003",
    bankId: "maribank",
    name: "MariBank - Daily Saver",
    principal: 1150000,
    startDate: "2026-02-01",
    termMonths: 12,
    interestMode: "tiered",
    interestTreatment: "payout",
    compounding: "daily",
    taxRateOverride: 0.2,
    flatRate: 0.0325,
    tiers: [
      { upTo: 1000000, rate: 0.0325 },
      { upTo: null, rate: 0.0375 },
    ],
    payoutFrequency: "monthly",
    isOpenEnded: true,
    status: "active",
  },
  {
    id: "td-004",
    bankId: "maya",
    name: "Maya - SA",
    principal: 140000,
    startDate: "2026-02-01",
    termMonths: 12,
    interestMode: "tiered",
    interestTreatment: "payout",
    compounding: "daily",
    taxRateOverride: 0.2,
    flatRate: 0.1,
    tiers: [
      { upTo: 100000, rate: 0.1 },
      { upTo: null, rate: 0.035 },
    ],
    payoutFrequency: "monthly",
    isOpenEnded: true,
    status: "active",
  },
  {
    id: "td-005",
    bankId: "cimb-prime",
    name: "CIMB Prime - 6M",
    principal: 500000,
    startDate: "2026-01-07",
    termMonths: 6,
    interestMode: "simple",
    interestTreatment: "reinvest",
    compounding: "monthly",
    taxRateOverride: 0.2,
    flatRate: 0.052,
    tiers: [{ upTo: null, rate: 0.052 }],
    payoutFrequency: "maturity",
    status: "active",
  },
  {
    id: "td-006",
    bankId: "cimb",
    name: "CIMB - 3M",
    principal: 250000,
    startDate: "2026-01-12",
    termMonths: 3,
    interestMode: "simple",
    interestTreatment: "reinvest",
    compounding: "monthly",
    taxRateOverride: 0.2,
    flatRate: 0.045,
    tiers: [{ upTo: null, rate: 0.045 }],
    payoutFrequency: "maturity",
    status: "active",
  },
  {
    id: "td-007",
    bankId: "uno",
    name: "UnoEarn - 24M",
    principal: 280000,
    startDate: "2026-02-05",
    termMonths: 24,
    interestMode: "simple",
    interestTreatment: "payout",
    compounding: "monthly",
    taxRateOverride: 0.2,
    flatRate: 0.05,
    tiers: [{ upTo: null, rate: 0.05 }],
    payoutFrequency: "monthly",
    status: "active",
  },
  {
    id: "td-008",
    bankId: "ownbank",
    name: "OwnBank - 90",
    principal: 150000,
    startDate: "2025-10-15",
    termMonths: 3,
    interestMode: "simple",
    interestTreatment: "reinvest",
    compounding: "monthly",
    taxRateOverride: 0.2,
    flatRate: 0.05,
    tiers: [{ upTo: null, rate: 0.05 }],
    payoutFrequency: "maturity",
    status: "matured",
  },
];
